### ISSUE TITLE
Media query support?

### ISSUE THREAD

**Issue by saulobraine** [charisTheo/css-nesting-tool#1]
Hey, I've try your tool, is really awesome, but in my tests this example:

`.css {
   @media (width >1024px) {
      color: white;
   }
}`

Returns empty.

**Comment by charisTheo** [comment]
Neither that or the following are supported at the moment:

From: 

```css
.css { 
  margin: 10px; 
}

@media (width > 1024px) { 
  .css {
    color: white; 
  } 
}
```

To: 

```css
.css {
  margin: 10px;

  @media (width > 1024px) {
   color: white;
  }
}
```

This is gonna take some time to figure out pros and cons of this approach and if it is more efficient in real-life scenarios. Feel free to drop a PR if you can and we can test it out.
